nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://cfthbordeaux.com', 'https://infinitygames.ddvportfolio.com', 'https://api.ddvportfolio.com', 'http://localhost:3000']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['https://cfthbordeaux.com', 'https://infinitygames.ddvportfolio.com', 'https://api.ddvportfolio.com', 'http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600